name: MusicDashboard
options:
  bundleIdPrefix: com.musicdashboard
  deploymentTarget:
    iOS: 16.0
    macOS: 12.0

targets:
  Services:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Services
    settings:
      DEFINES_MODULE: YES
      SWIFT_INSTALL_OBJC_HEADER: NO
      SWIFT_EMIT_OBJC_HEADER: NO
      CLANG_ENABLE_MODULES: NO
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.Services
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
    
  Components:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Views/Components
    dependencies:
      - target: Services
    settings:
      DEFINES_MODULE: YES
      SWIFT_INSTALL_OBJC_HEADER: NO
      SWIFT_EMIT_OBJC_HEADER: NO
      CLANG_ENABLE_MODULES: NO
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.Components
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
    
  SharedViews:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Views/SharedViews
    dependencies:
      - target: Services
      - target: Components
    settings:
      DEFINES_MODULE: YES
      SWIFT_INSTALL_OBJC_HEADER: NO
      SWIFT_EMIT_OBJC_HEADER: NO
      CLANG_ENABLE_MODULES: NO
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.SharedViews
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
    
  AuthViews:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Views/AuthViews
    dependencies:
      - target: Services
      - target: Components
    settings:
      DEFINES_MODULE: YES
      SWIFT_INSTALL_OBJC_HEADER: NO
      SWIFT_EMIT_OBJC_HEADER: NO
      CLANG_ENABLE_MODULES: NO
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.AuthViews
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
    
  NewsViews:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Views/NewsViews
    dependencies:
      - target: Services
      - target: Components
    settings:
      DEFINES_MODULE: YES
      SWIFT_INSTALL_OBJC_HEADER: NO
      SWIFT_EMIT_OBJC_HEADER: NO
      CLANG_ENABLE_MODULES: NO
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.NewsViews
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
    
  MusicViews:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Views/MusicViews
    dependencies:
      - target: Services
      - target: Components
    settings:
      DEFINES_MODULE: YES
      SWIFT_INSTALL_OBJC_HEADER: NO
      SWIFT_EMIT_OBJC_HEADER: NO
      CLANG_ENABLE_MODULES: NO
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.MusicViews
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
    
  MusicDashboard:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "Views/MusicViews/**"
          - "Views/Components/**"
          - "Views/SharedViews/**"
          - "Views/AuthViews/**"
          - "Views/NewsViews/**"
          - "Services/**"
          - "Models/**"
      - path: Resources
    dependencies:
      - target: MusicViews
      - target: Components
      - target: SharedViews
      - target: AuthViews
      - target: NewsViews
      - target: Services
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/MusicDashboard.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.app
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
