name: MusicDashboard
options:
  bundleIdPrefix: com.musicdashboard
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "14.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: 4Y39R5M676
    PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.app
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait

targets:
  MusicDashboard:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "Services/SpotifyService.swift"
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=100"
        CODE_SIGN_ENTITLEMENTS: Sources/MusicDashboard.entitlements
        ENABLE_BACKGROUND_MODES: YES
        INFOPLIST_KEY_UIBackgroundModes:
          - audio
          - fetch
        PRODUCT_BUNDLE_CAPABILITIES:
          - com.apple.developer.playable-content
          - com.apple.developer.music-kit
    entitlements:
      path: Sources/MusicDashboard.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.personal-information.music-library: true
        com.apple.developer.music-kit: true
        com.apple.developer.playable-content: true
        com.apple.runningboard.sonic: true
        com.apple.security.temporary-exception.mach-lookup.global-name: 
          - com.apple.identityservicesd
          - com.apple.accountsd
          - com.apple.musicstorefrontend
          - com.apple.coreservices.appleaccountd
          - com.apple.askpermissiond
        com.apple.security.temporary-exception.files.home-relative-path.read-write:
          - Library/Application Support/com.apple.MediaPlayer/ServerObjectDatabases
          - Library/Caches/com.apple.Music
          - Library/Accounts
          - Library/Preferences/com.apple.accounts.plist
        com.apple.security.temporary-exception.apple-events:
          - com.apple.iTunes
          - com.apple.Music
          - com.apple.accountsd
        com.apple.security.application-groups:
          - group.com.musicdashboard.app
        com.apple.security.temporary-exception.sbpl:
          - (allow mach-lookup (global-name "com.apple.accountsd"))
          - (allow file-read* file-write* (subpath "/private/var/mobile/Library/Accounts"))
    
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Music Dashboard
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
