name: MusicDashboard
options:
  bundleIdPrefix: com.musicdashboard
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "14.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: 4Y39R5M676
    PRODUCT_BUNDLE_IDENTIFIER: com.musicdashboard.app
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait

targets:
  MusicDashboard:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=100"
        CODE_SIGN_ENTITLEMENTS: Sources/MusicDashboard.entitlements
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
        ENABLE_BACKGROUND_MODES: YES
        INFOPLIST_KEY_UIBackgroundModes:
          - audio
          - fetch
        PRODUCT_BUNDLE_CAPABILITIES:
          - com.apple.developer.musickit.service
          - com.apple.developer.icloud-services
          - com.apple.developer.icloud-container-identifiers
          - com.apple.developer.icloud-container-environment
    entitlements:
      path: Sources/MusicDashboard.entitlements
      properties:
        com.apple.developer.musickit.service: true
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.musicdashboard.stats
        com.apple.developer.icloud-container-environment: Production
    
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Music Dashboard
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
